name: reso_tdd
description: TDD Clean Architextture for Flutter Updated with Null Safety.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^7.3.0
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.0-nullsafety.2
  # Remote API
  http: ^0.13.3
  # Local cache
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
